# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=20)),
                ('singer', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('play', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.IntegerField()),
                ('site', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Store'),
        ),
    ]
